spring:
  application:
    name: backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

  validation:
    enabled: true
    
  mvc:
    static-path-pattern: /uploads/** # Add this line

  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${file-upload.path} # Use the configured path

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
    default-encoding: UTF-8

server:
  servlet:
    context-path: /api/v1
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file-upload:
  path: ./uploads/projects/

base-url: http://localhost:8080
# Spring Security (Optional if needed)
# security:
#   user:
#     name: admin
#     password: admin1234
