spring:
  application:
    name: backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

  validation:
    enabled: true

  mvc:
    static-path-pattern: /uploads/** # Static resource mapping for uploaded files

  web:
    resources:
      static-locations:
        - classpath:/static/         # Default location for app static resources
        - file:${file-upload.paths.project}  # Project uploads
        - file:${file-upload.paths.hero}     # Hero images
        - file:${file-upload.paths.about}    # About section files
        - file:${file-upload.paths.logo}     # Logo files
        - file:${file-upload.paths.cover}    # Cover images
        - file:${file-upload.paths.resume}   # Resume files
        - file:${file-upload.paths.contact}  # Contact section uploads

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
    default-encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 50MB # Unified file size configuration
      max-request-size: 50MB

server:
  servlet:
    context-path: /api/v1 # Base context path for APIs

file-upload:
  paths:
    project: ./uploads/project/ # Directory for project uploads
    hero: ./uploads/hero/       # Directory for hero images
    about: ./uploads/about/     # Directory for "About" section files
    logo: ./uploads/logo/       # Directory for logo files
    cover: ./uploads/cover/     # Directory for cover images
    resume: ./uploads/resume/   # Directory for resumes
    contact: ./uploads/contact/ # Directory for contact-related uploads

base-url: http://localhost:8080

# Uncomment and configure if Spring Security is needed
# security:
#   user:
#     name: admin
#     password: admin1234
